[package]
name = "pretix-webhook-cli"
version.workspace = true
description = "Command-line pretix webhook receiver"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[[bin]]
name = "pretix-webhook"
path = "src/main.rs"
doc = false

[dependencies]
pretix-webhook = { workspace = true, features = ["tracing"] }

axum = { workspace = true, features = ["http1", "tokio"] }
clap = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["net", "signal", "sync"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
temp-env = { workspace = true }
tower = { workspace = true }

[lints]
workspace = true
