[package]
name = "pretix-webhook-events"
version.workspace = true
description = "Typed event payloads sent by pretix webhooks"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["pretix", "webhook", "events"]
categories = ["data-structures"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
